# Generated by Django 5.1.3 on 2025-01-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Введите название категории (например, 'JavaScript', 'Python').", max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(help_text='Введите описание категории.', verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='Введите текст вопроса, который будет отображаться студентам.', verbose_name='Текст вопроса')),
                ('answer', models.TextField(help_text='Введите правильный ответ на вопрос.', verbose_name='Ответ на вопрос')),
                ('category', models.ForeignKey(help_text='Выберите категорию для этого вопроса.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
