# Generated by Django 5.1.3 on 2025-02-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField(help_text='Введите количество секунд для таймера', verbose_name='Секунды')),
            ],
            options={
                'verbose_name': 'Таймер',
                'verbose_name_plural': 'Таймеры',
                'db_table': 'timers',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(help_text='Введите текст', verbose_name='Содержание текста')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='Typing.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
                'db_table': 'texts',
            },
        ),
    ]
