# Generated by Django 5.1.3 on 2025-03-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название категории видео', max_length=100, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория видео',
                'verbose_name_plural': 'Категории видео',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название видео', max_length=200, verbose_name='Название видео')),
                ('description', models.TextField(blank=True, help_text='Добавьте краткое описание видео', null=True, verbose_name='Описание видео')),
                ('video_url', models.URLField(help_text='Введите ссылку на YouTube видео', verbose_name='URL видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время добавления видео', verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, help_text='Установите в False, чтобы деактивировать видео', verbose_name='Активно')),
                ('video_category', models.ForeignKey(help_text='Выберите категорию для видео', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Video.videocategory', verbose_name='Категория видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
