# Generated by Django 5.1.3 on 2025-03-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('code', models.CharField(max_length=6, verbose_name='OTP код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания OTP')),
            ],
        ),
    ]
