# Generated by Django 5.1.3 on 2025-03-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created_at',
        ),
    ]
