# Generated by Django 5.1.3 on 2025-02-23 11:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи.', verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Введите название группы (до 150 символов).', max_length=150, verbose_name='Название группы')),
                ('created_by', models.ForeignKey(help_text='Пользователь, создавший эту запись.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи')),
                ('updated_user', models.ForeignKey(blank=True, help_text='Пользователь, последний изменивший эту запись.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Последний изменивший')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='HistoricalGroup',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время создания записи.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время последнего обновления записи.', verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Введите название группы (до 150 символов).', max_length=150, verbose_name='Название группы')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, создавший эту запись.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последний изменивший эту запись.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Последний изменивший')),
            ],
            options={
                'verbose_name': 'historical Группа',
                'verbose_name_plural': 'historical Группы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время создания записи.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Дата и время последнего обновления записи.', verbose_name='Дата обновления')),
                ('full_name', models.CharField(help_text='Введите полное имя студента (до 150 символов).', max_length=150, verbose_name='ФИО студента')),
                ('is_active', models.BooleanField(default=False, help_text='Отметьте, если студент активен в системе.', verbose_name='Активность студента')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, создавший эту запись.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Groups.group')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(blank=True, db_constraint=False, help_text='Пользователь, последний изменивший эту запись.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Последний изменивший')),
            ],
            options={
                'verbose_name': 'historical Студент',
                'verbose_name_plural': 'historical Студенты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи.', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления записи.', verbose_name='Дата обновления')),
                ('full_name', models.CharField(help_text='Введите полное имя студента (до 150 символов).', max_length=150, verbose_name='ФИО студента')),
                ('is_active', models.BooleanField(default=False, help_text='Отметьте, если студент активен в системе.', verbose_name='Активность студента')),
                ('created_by', models.ForeignKey(help_text='Пользователь, создавший эту запись.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель записи')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='Groups.group')),
                ('updated_user', models.ForeignKey(blank=True, help_text='Пользователь, последний изменивший эту запись.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Последний изменивший')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'students',
            },
        ),
    ]
